version: '2.2'
services:
  www:
    image: nginx
    volumes:
      - "./www:/usr/share/nginx/html"
      - "./www/nginx.conf:/etc/nginx/conf.d/toyca.conf"
      - "./ca:/etc/ssl/toyca"
    ports:
      - "127.0.0.1:1443:1443"
      - "127.0.0.1:2443:2443"
      - "127.0.0.1:3443:3443"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:5443:5443"
      - "127.0.0.1:6443:6443"
      - "127.0.0.1:7443:7443"
    hostname: ca.example.com
  proxy:
    image: squid
    volumes:
      - "./www/squid.conf:/etc/squid/squid.conf"
    hostname: proxy.example.com
