# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'ToyCA'
copyright = '2020, mo'
author = 'mo'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.todo',
    'sphinxcontrib.blockdiag',
    'sphinxcontrib.seqdiag',
    'sphinxcontrib.actdiag',
    'sphinxcontrib.nwdiag',
    'sphinxcontrib.rackdiag',
    'sphinxcontrib.packetdiag',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['exclude-*.md', 'node_modules']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# template
source_suffix = {
    '.rst':'restructuredtext',
    '.md':'markdown',
}

# source_parsers = {
#     '.md': CustomCommonMarkParser,
# }

latex_elements = {
    'papersize': 'a4paper',
    'classoptions': ',dvipdfmx'
}

#[parser: multiple warning messages due to missing visit_document() method · Issue #177 · readthedocs/recommonmark](https://github.com/readthedocs/recommonmark/issues/177)
from recommonmark.parser import CommonMarkParser
class CustomCommonMarkParser(CommonMarkParser):
    def visit_document(self, node):
        pass
from recommonmark.transform import AutoStructify
def setup(app):
    github_doc_root = 'https://github.com/rtfd/recommonmark/tree/master/doc/'
    app.add_config_value('recommonmark_config', {
        'url_resolver': lambda url: github_doc_root + url,
        'auto_toc_tree_section': 'Contents',
    }, True)
    app.add_transform(AutoStructify)
    app.add_source_parser(CustomCommonMarkParser)

blockdiag_html_image_format = 'SVG'
seqdiag_html_image_format = 'SVG'
actdiag_html_image_format = 'SVG'
nwdiag_html_image_format = 'SVG'
rackiag_html_image_format = 'SVG'
packetdiag_html_image_format = 'SVG'

blockdiag_latex_image_format = 'PDF'
seqdiag_latex_image_format = 'PDF'
actdiag_latex_image_format = 'PDF'
nwdiag_latex_image_format = 'PDF'
rackiag_latex_image_format = 'PDF'
packetdiag_latex_image_format = 'PDF'

latex_docclass = {'manual': 'jsbook'}
latex_engine = 'platex'

actdiag_fontpath = '/usr/share/fonts/truetype/takao-gothic/TakaoPGothic.ttf'
blockdiag_fontpath = '/usr/share/fonts/truetype/takao-gothic/TakaoPGothic.ttf'

# html_context = {
#     'css_files': [
#         '_static/overrides.css',  # overrides for wide tables in RTD theme
#     ],
# }

numfig = True
todo_include_todos = True
autosectionlabel_prefix_document = True
