version: '2.2'
services:
  www:
    image: nginx:alpine
#    image: nginx
    volumes:
      - "../www:/usr/share/nginx/html"
      - "../www/nginx.conf:/etc/nginx/conf.d/toyca.conf"
      - "../ca:/etc/ssl/toyca"
    ports:
      - "127.0.0.1:1443:1443"
      - "127.0.0.1:2443:2443"
      - "127.0.0.1:3443:3443"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:5443:5443"
      - "127.0.0.1:6443:6443"
      - "127.0.0.1:7443:7443"
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:8445:8445"
    hostname: ca.example.com
  proxy:
    image: squid-bump
    ports:
      - "127.0.0.1:3128:3128"
    hostname: proxy.example.com
  openssl:
    image: openssl-tls1_3
    tty: true
    volumes:
      - "..:/opt/toyca"
    hostname: openssl.example.com
    links:
      - www:ca.example.com
      - proxy:proxy.example.com
  ocsp:
    image: mattbodholdt/openca-ocspd
    volumes:
      - "../ca/server-ca-1/certs/ocsp.example.com/cert.pem:/data/ocspd/ocspd.crt"
      - "../ca/server-ca-1/certs/ocsp.example.com/key.pem:/data/ocspd/ocspd.key"
      - "../ca/server-ca-1/cacert.pem:/data/ocspd/ca.crt"
      - "../www/server-ca-1.crl:/data/ocspd/crl.crl"
    ports:
      - "127.0.0.1:2560:2560"
    hostname: ocsp.example.com
  caddy:
    image: abiosoft/caddy
    volumes:
      - "../Caddyfile:/etc/Caddyfile"
      - "../ca:/etc/ssl/toyca"
    ports:
      - "127.0.0.1:2015:2015"
      - "127.0.0.1:8444:8444"
      - "127.0.0.1:8444:8444/udp"
      # - "127.0.0.1:8445:8445"
      # - "127.0.0.1:8445:8445/udp"
    hostname: caddy.example.com
    command:
      - --conf
      - /etc/Caddyfile
      - --log
      - stdout
      - -quic
